### ISSUE TITLE
Task List 작성 테스트

### ISSUE THREAD

**Issue by hyenny** [hyenny/git_test#4]
- [x] Write the code
- [x] Write all the test
- [x] Document the code
